// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/wasya-io/go-kilo/app/entity/core (interfaces: Logger,LogEntry)

// Package mock_core is a generated GoMock package.
package mock_core

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	core "github.com/wasya-io/go-kilo/app/entity/core"
)

// MockLogger is a mock of Logger interface.
type MockLogger struct {
	ctrl     *gomock.Controller
	recorder *MockLoggerMockRecorder
}

// MockLoggerMockRecorder is the mock recorder for MockLogger.
type MockLoggerMockRecorder struct {
	mock *MockLogger
}

// NewMockLogger creates a new mock instance.
func NewMockLogger(ctrl *gomock.Controller) *MockLogger {
	mock := &MockLogger{ctrl: ctrl}
	mock.recorder = &MockLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogger) EXPECT() *MockLoggerMockRecorder {
	return m.recorder
}

// Flush mocks base method.
func (m *MockLogger) Flush() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Flush")
}

// Flush indicates an expected call of Flush.
func (mr *MockLoggerMockRecorder) Flush() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Flush", reflect.TypeOf((*MockLogger)(nil).Flush))
}

// Log mocks base method.
func (m *MockLogger) Log(arg0, arg1 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Log", arg0, arg1)
}

// Log indicates an expected call of Log.
func (mr *MockLoggerMockRecorder) Log(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Log", reflect.TypeOf((*MockLogger)(nil).Log), arg0, arg1)
}

// ReadyWithType mocks base method.
func (m *MockLogger) ReadyWithType(arg0 string) core.LogEntry {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadyWithType", arg0)
	ret0, _ := ret[0].(core.LogEntry)
	return ret0
}

// ReadyWithType indicates an expected call of ReadyWithType.
func (mr *MockLoggerMockRecorder) ReadyWithType(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadyWithType", reflect.TypeOf((*MockLogger)(nil).ReadyWithType), arg0)
}

// MockLogEntry is a mock of LogEntry interface.
type MockLogEntry struct {
	ctrl     *gomock.Controller
	recorder *MockLogEntryMockRecorder
}

// MockLogEntryMockRecorder is the mock recorder for MockLogEntry.
type MockLogEntryMockRecorder struct {
	mock *MockLogEntry
}

// NewMockLogEntry creates a new mock instance.
func NewMockLogEntry(ctrl *gomock.Controller) *MockLogEntry {
	mock := &MockLogEntry{ctrl: ctrl}
	mock.recorder = &MockLogEntryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogEntry) EXPECT() *MockLogEntryMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockLogEntry) Do(arg0 ...interface{}) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Do", varargs...)
}

// Do indicates an expected call of Do.
func (mr *MockLogEntryMockRecorder) Do(arg0 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockLogEntry)(nil).Do), arg0...)
}

// WithInt mocks base method.
func (m *MockLogEntry) WithInt() core.LogEntry {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithInt")
	ret0, _ := ret[0].(core.LogEntry)
	return ret0
}

// WithInt indicates an expected call of WithInt.
func (mr *MockLogEntryMockRecorder) WithInt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithInt", reflect.TypeOf((*MockLogEntry)(nil).WithInt))
}

// WithString mocks base method.
func (m *MockLogEntry) WithString() core.LogEntry {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithString")
	ret0, _ := ret[0].(core.LogEntry)
	return ret0
}

// WithString indicates an expected call of WithString.
func (mr *MockLogEntryMockRecorder) WithString() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithString", reflect.TypeOf((*MockLogEntry)(nil).WithString))
}

// WithType mocks base method.
func (m *MockLogEntry) WithType() core.LogEntry {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithType")
	ret0, _ := ret[0].(core.LogEntry)
	return ret0
}

// WithType indicates an expected call of WithType.
func (mr *MockLogEntryMockRecorder) WithType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithType", reflect.TypeOf((*MockLogEntry)(nil).WithType))
}
