// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/wasya-io/go-kilo/app/boundary/writer (interfaces: ScreenWriter)

// Package mock_writer is a generated GoMock package.
package mock_writer

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockScreenWriter is a mock of ScreenWriter interface.
type MockScreenWriter struct {
	ctrl     *gomock.Controller
	recorder *MockScreenWriterMockRecorder
}

// MockScreenWriterMockRecorder is the mock recorder for MockScreenWriter.
type MockScreenWriterMockRecorder struct {
	mock *MockScreenWriter
}

// NewMockScreenWriter creates a new mock instance.
func NewMockScreenWriter(ctrl *gomock.Controller) *MockScreenWriter {
	mock := &MockScreenWriter{ctrl: ctrl}
	mock.recorder = &MockScreenWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScreenWriter) EXPECT() *MockScreenWriterMockRecorder {
	return m.recorder
}

// Write mocks base method.
func (m *MockScreenWriter) Write(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Write indicates an expected call of Write.
func (mr *MockScreenWriterMockRecorder) Write(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockScreenWriter)(nil).Write), arg0)
}
