// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/wasya-io/go-kilo/app/boundary/provider/input (interfaces: Provider)

// Package mock_input is a generated GoMock package.
package mock_input

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	key "github.com/wasya-io/go-kilo/app/entity/key"
)

// MockProvider is a mock of Provider interface.
type MockProvider struct {
	ctrl     *gomock.Controller
	recorder *MockProviderMockRecorder
}

// MockProviderMockRecorder is the mock recorder for MockProvider.
type MockProviderMockRecorder struct {
	mock *MockProvider
}

// NewMockProvider creates a new mock instance.
func NewMockProvider(ctrl *gomock.Controller) *MockProvider {
	mock := &MockProvider{ctrl: ctrl}
	mock.recorder = &MockProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProvider) EXPECT() *MockProviderMockRecorder {
	return m.recorder
}

// GetInputEvents mocks base method.
func (m *MockProvider) GetInputEvents() (key.KeyEvent, []key.KeyEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInputEvents")
	ret0, _ := ret[0].(key.KeyEvent)
	ret1, _ := ret[1].([]key.KeyEvent)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetInputEvents indicates an expected call of GetInputEvents.
func (mr *MockProviderMockRecorder) GetInputEvents() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInputEvents", reflect.TypeOf((*MockProvider)(nil).GetInputEvents))
}
